// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-anomaly-codes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.24.0";
var ANOMALIE_CODES = [
  { code: "01", libelle: "Compteur inaccessible" },
  { code: "02", libelle: "Absent avis de passage laiss\xE9" },
  { code: "03", libelle: "Compteur bloqu\xE9" },
  { code: "04", libelle: "Compteur cass\xE9" },
  { code: "05", libelle: "Compteur illisible / embu\xE9" },
  { code: "06", libelle: "Fuite apr\xE8s compteur" },
  { code: "07", libelle: "Fuite avant compteur" },
  { code: "08", libelle: "Compteur d\xE9pos\xE9" },
  { code: "09", libelle: "Compteur invers\xE9" },
  { code: "10", libelle: "Chien / acc\xE8s dangereux" },
  { code: "11", libelle: "Local ferm\xE9" },
  { code: "12", libelle: "Compteur noy\xE9" },
  { code: "13", libelle: "Point de livraison introuvable" },
  { code: "14", libelle: "Num\xE9ro de compteur non conforme" },
  { code: "15", libelle: "Consommation anormalement \xE9lev\xE9e" },
  { code: "16", libelle: "Consommation nulle" },
  { code: "17", libelle: "Compteur remplac\xE9" },
  { code: "18", libelle: "Immeuble d\xE9moli / vacant" }
];
var ANNULATION_CODES = [
  { code: "A1", libelle: "Erreur de saisie" },
  { code: "A2", libelle: "Doublon de rel\xE8ve" },
  { code: "A3", libelle: "Mauvais abonn\xE9" }
];
var list_anomaly_codes_default = defineTool({
  name: "list_reference_codes",
  title: "Lister les codes de r\xE9f\xE9rence",
  description: "Retourne les codes d'anomalie et d'annulation utilis\xE9s lors de la rel\xE8ve des compteurs d'eau SEACO.",
  inputSchema: {
    type: z.enum(["anomalie", "annulation", "all"]).default("all").describe("Type de codes \xE0 retourner")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ type }) => {
    const payload = {};
    if (type === "anomalie" || type === "all") payload.anomalies = ANOMALIE_CODES;
    if (type === "annulation" || type === "all") payload.annulations = ANNULATION_CODES;
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/validate-meter-reading.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.24.0";
var validate_meter_reading_default = defineTool2({
  name: "validate_meter_reading",
  title: "Valider un relev\xE9 de compteur",
  description: "Compare un nouvel index \xE0 l'ancien, calcule la consommation en m\xB3 et signale les anomalies probables (retour arri\xE8re, consommation nulle, d\xE9passement de seuil).",
  inputSchema: {
    ancienIndex: z2.number().nonnegative().describe("Ancien index en m\xB3"),
    nouvelIndex: z2.number().nonnegative().describe("Nouvel index relev\xE9 en m\xB3"),
    seuilAlerte: z2.number().positive().default(200).describe("Consommation en m\xB3 au-del\xE0 de laquelle un signalement est \xE9mis")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ ancienIndex, nouvelIndex, seuilAlerte }) => {
    const consommation = nouvelIndex - ancienIndex;
    const anomalies = [];
    if (nouvelIndex < ancienIndex) {
      anomalies.push(
        "INDEX_REGRESSIF: le nouvel index est inf\xE9rieur \xE0 l'ancien (compteur remplac\xE9 ou erreur de saisie)."
      );
    }
    if (consommation === 0) {
      anomalies.push("CONSOMMATION_NULLE: aucune consommation d\xE9tect\xE9e sur la p\xE9riode.");
    }
    if (consommation > seuilAlerte) {
      anomalies.push(
        `CONSOMMATION_ELEVEE: ${consommation} m\xB3 d\xE9passe le seuil d'alerte de ${seuilAlerte} m\xB3 (fuite possible).`
      );
    }
    const result = {
      ancienIndex,
      nouvelIndex,
      consommation,
      seuilAlerte,
      valide: anomalies.length === 0,
      anomalies
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "seaco-releve-eau-mcp",
  title: "SEACO \u2014 Rel\xE8ve d'Eau MCP",
  version: "0.1.0",
  instructions: "Outils utilitaires publics pour l'application SEACO \u2014 Rel\xE8ve d'Eau. Permet aux assistants IA de consulter les codes d'anomalie/annulation et de valider un relev\xE9 de compteur (calcul de consommation, d\xE9tection d'anomalies). Aucune donn\xE9e d'abonn\xE9 n'est expos\xE9e.",
  tools: [list_anomaly_codes_default, validate_meter_reading_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
